name: Deploy Production to Lightsail
on:
  push:
    branches: [lightsail]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Lightsail Production
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            # Preserve .env.production and clean setup
            if [ -f /opt/mizual/.env.production ]; then
              cp /opt/mizual/.env.production /tmp/.env.production.backup
            fi
            sudo rm -rf /opt/mizual
            sudo mkdir -p /opt/mizual
            sudo chown ubuntu:ubuntu /opt/mizual
            cd /opt/mizual
            git clone https://github.com/vizualtech-007/mizual-backend.git .
            git checkout lightsail
            # Restore .env.production
            if [ -f /tmp/.env.production.backup ]; then
              cp /tmp/.env.production.backup .env.production
            fi
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --build
            
      - name: Health Check
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            sleep 30
            curl -f http://localhost:8000/health || exit 1
            echo "Production deployment successful!"