name: Setup AWS Parameter Store from GitHub Secrets

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  setup-parameter-store:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Parameter Store for DEV environment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          echo "Setting up DEV parameters in AWS Parameter Store..."
          
          # Parse ENV_FILE_DEV and upload to Parameter Store
          echo "${{ secrets.ENV_FILE_DEV }}" | while IFS='=' read -r key value || [ -n "$key" ]; do
            # Skip comments and empty lines
            [[ $key =~ ^[[:space:]]*# ]] && continue
            [[ -z $key ]] && continue
            
            # Clean up key (remove leading/trailing whitespace)
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)
            
            # Skip if key or value is empty after cleaning
            [[ -z $key || -z $value ]] && continue
            
            echo "Processing: $key"
            
            # Determine parameter type (SecureString for sensitive values)
            if [[ $key =~ (API_KEY|SECRET|PASSWORD|URL|DATABASE_URL|ACCESS_KEY) ]]; then
              param_type="SecureString"
            else
              param_type="String"
            fi
            
            # Convert to lowercase for parameter name
            param_name=$(echo "$key" | tr '[:upper:]' '[:lower:]')
            
            # Upload to Parameter Store
            aws ssm put-parameter \
              --name "/mizual/$param_name" \
              --value "$value" \
              --type "$param_type" \
              --description "DEV: Auto-imported from GitHub Secrets $(date)" \
              --overwrite || echo "Failed to create parameter: $param_name"
          done
          
      - name: Setup Parameter Store for PROD environment  
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          echo "Setting up PROD parameters in AWS Parameter Store..."
          
          # Parse ENV_FILE_PROD and upload to Parameter Store
          echo "${{ secrets.ENV_FILE_PROD }}" | while IFS='=' read -r key value || [ -n "$key" ]; do
            # Skip comments and empty lines
            [[ $key =~ ^[[:space:]]*# ]] && continue
            [[ -z $key ]] && continue
            
            # Clean up key (remove leading/trailing whitespace)
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)
            
            # Skip if key or value is empty after cleaning
            [[ -z $key || -z $value ]] && continue
            
            echo "Processing: $key"
            
            # Determine parameter type (SecureString for sensitive values)
            if [[ $key =~ (API_KEY|SECRET|PASSWORD|URL|DATABASE_URL|ACCESS_KEY) ]]; then
              param_type="SecureString"
            else
              param_type="String"
            fi
            
            # Convert to lowercase for parameter name
            param_name=$(echo "$key" | tr '[:upper:]' '[:lower:]')
            
            # Upload to Parameter Store
            aws ssm put-parameter \
              --name "/mizual/$param_name" \
              --value "$value" \
              --type "$param_type" \
              --description "PROD: Auto-imported from GitHub Secrets $(date)" \
              --overwrite || echo "Failed to create parameter: $param_name"
          done

      - name: Verify DEV parameter upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          echo "=== DEV Parameters Created ==="
          aws ssm get-parameters-by-path \
            --path "/mizual" \
            --recursive \
            --query 'Parameters[*].[Name,Type]' \
            --output table || echo "No DEV parameters found"
          
      - name: Verify PROD parameter upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          echo "=== PROD Parameters Created ==="
          aws ssm get-parameters-by-path \
            --path "/mizual" \
            --recursive \
            --query 'Parameters[*].[Name,Type]' \
            --output table || echo "No PROD parameters found"
            
      - name: Setup Summary
        run: |
          echo "✅ Parameter Store setup completed!"
          echo ""
          echo "Next steps:"
          echo "1. Check AWS Console → Systems Manager → Parameter Store in both accounts"
          echo "2. Verify all parameters are visible and correctly typed"
          echo "3. Test deployment workflow with Parameter Store integration"
          echo "4. After successful validation, remove ENV_FILE_DEV and ENV_FILE_PROD GitHub Secrets"